AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Appraisals'
  Exclude:
    - 'spec/dummy/**/*'
    - 'lib/generators/**/*'
  SuggestExtensions: false

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 150

require:
  - rubocop-rails

# DISABLED

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
